#+TITLE: UAP Five body weight workouts
#+SETUPFILE: ../phase.setup

* Upper body strength (10 min)
   This short session is a good intro to some body weight work for the upper body. Go beyond the pushup and into some interesting alternatives in this short, but effective training session!

   Do each of the exercises for the recommended repetitions. Repeat the circuit 2-3 times.

   | Exercise |  Reps |
   |----------+-------|
   | A1       | 10-25 |
   | A2       |  6-20 |
   | A3       | 10-20 |

** A1. Rocking Pushups

    https://fast.wistia.net/embed/iframe/pc2ii2vih2
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/QI2x1GaQke1AuYofcnqK_Rocking_Pushups_1.jpg

    This is a great exercise for naturally cueing good pushup form. It is far superior to pushups from the knees for those who cannot do full pushups because the spine tends to maintain the preferred alignment throughout the movement and the elbows stay tucked in.

    For those strong enough for a high volume of regular pushups, the rocking pushup is an excellent upper body warm-up exercise that cues good form, and moves the shoulder through a large range of motion.

** A2. Side-to-Side Monkey Crawl

    https://fast.wistia.net/embed/iframe/ibf0bw3evg
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/yeSc9utYS9uflj1cGWHp_Side-to-Side_Monkey_Crawl_1.jpg

    One rep includes both sides.

    This Monkey Crawl exercise gives us a bit of rotational core stimulus and is good for training shoulder stability. As you get better at the exercise you can move your hips higher and move more slowly.

** A3. Wall-Catch Pushups

    https://fast.wistia.net/embed/iframe/q9s2q8n6m3
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/AtTKbDfRFepN6gszwk2w_Wall-Catch_Pushups_1.jpg

    The goal of this exercise is to “catch” yourself with the elbows at about 90 degrees. This engages the muscle fibers of the pectorals very quickly. It adds a bit of power stimulus to your upper body routine.

    If this exercise is too easy, you can also do catch pushups on the floor from your knees. Start with just a few reps. It's easy to overdo it on fast eccentric exercises until you get used to them!

* Conditioning (10 min)
   This session involves lots of jumping! So get your sneakers on and just follow along with these guys.

   This workout is one of our indoor conditioning sessions in the UAP. Brought to you by former Pitt captain, Jonah Wisch!

   You'll need 10mins for the workout, and all the instructions are written on screen so you can listen to any tunes you like!

   Go through this circuit 2x this week and up to 3x as you build up endurance. Rest 1-2 minutes between circuits. This workout can be done 1-2 times/week.

    https://fast.wistia.net/embed/iframe/bjdiqqaa6p
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/GZo5ZExsR1KT6ejb57LX_Indoor_Conditioning.png

* Lower body strength (30 min)
   Today we are doing three pairs of exercises. The first two are primarily for warm up and activation. The second pair is the primary focus of the workout. The last pair of exercises are supporting exercises, one primarily for injury risk reduction.

   You might prefer sneakers or you might prefer doing these exercises barefoot on a yoga mat or other soft surface. Either way will work.

   | Sets | Sequence              | Rest | Rest between sets |
   |------+-----------------------+------+-------------------|
   |    3 | 10xA1 - 10xA2         | 0 s  | 60 s              |
   |    3 | 10xB1 - 10xB2         | 0 s  | 60 s              |
   |    3 | 20xC1 - 10xC2         | 0 s  | 60 s              |

** A1. Plie Squat
   This exercise is important because it targets the inner thigh/groin in the kind of way that it is used for activities like marking, lunging, and throwing with the hip externally rotated.

** A2. Cook Hip Lift
   Excellent exercise for glute activation. Keeping the knee tight toward the chest prevents compensation patterns like arching the back instead of squeezing the glute.

   https://fast.wistia.net/embed/iframe/yc232uhyji
   https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/qzRw2sywT6aNBNDPmtMT_file.jpg

** B1. Catch Squat
   Excellent exercise for glute activation. Keeping the knee tight toward the chest prevents compensation patterns like arching the back instead of squeezing the glute.

   https://fast.wistia.net/embed/iframe/qtse3dilo1
   https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/kRDwtsqcQ6yNBXUBgchX_file.jpg

** B2. Sprinter Start & Step
   The goal of this exercise is to explosively use your glutes and hamstring to push you forward.

   https://fast.wistia.net/embed/iframe/vk8l2ta2cr
   https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/DV5osbxBTli8nHTcvWaX_sprinterStart_1.jpg

** C1. Calf Raises
   Go the whole way up on the balls of your feet for a full range of motion.

   https://fast.wistia.net/embed/iframe/tnvkk11yzi
   https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/vu58ri6TAGkJbR0CwXRA_calfRaises_1.jpg

** C2. Standing Hip Flexion
   This exercise targets the hip flexor. The use of a bench or chair is mainly so that you can tell if your leg is slowly dropping lower.

   https://fast.wistia.net/embed/iframe/wdgkodyyxf
   https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/nZYA3zBhQsy7gu7rHFt1_hipFlexion_1.jpg

* Conditioning (6 min per set)
   Do each exercise for AMRAP in 30 seconds. Move immediately to the next exercise. Alternatively rest 15-30 seconds before moving on to the next exercise.

   The first week, go through the circuit only once. This workout can be done up to three times per week.

   Progress can be measured by:

   Decreasing your rest between exercises or not resting at all
   Doing more repetitions
   Finishing the circuit more quickly (same number reps, done faster)
   Building up to going through the circuit up to three times.

   The circuit consists of these exercises (click for an explanation of form, along with a demo)

   https://www.youtube.com/watch?v=DbvYVs_TgZM

   1. Rocking Push-up
   2. Hindu Squat
   3. Monkey Crawl
   4. Fireman drill
   5. Catch squat
   6. Sprinter-start Lunge
   7. Donkey Kick
   8. Karate-kick lunge
   9. Catcher squat
   10. Alternate Crab/Bear
   11. Helicopter
   12. Glute Bridge

* Full body strength endurance

   | Sets | Sequence          |
   |------+-------------------|
   |    2 | 6-20xA1 - 6-20xA2 |
   |    2 | 6-20xB1 - 6-20xB2 |
   |    2 | 6-20xC1 - 6-20xC2 |

** A1. Pike Push-up
    https://fast.wistia.net/embed/iframe/telkbzhtkq
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/6GcJ9c8MTQWMxjMYBbmq_Rocking_Pushups.png
** A2. Bodyweight Squat
    https://fast.wistia.net/embed/iframe/2roptxntu9
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/Bf4hqZJRJCF4hzP2URg5_Bodyweight_Squat.png
** B1. Speed Push-up
    https://fast.wistia.net/embed/iframe/8nvrz89jrn
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/bsqiTnrWS0asjB471LST_Speed_Push-up.png
** B2. Diagonal Lunge
    https://fast.wistia.net/embed/iframe/w01ht14jk3
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/RzXuVHx0Tnq2ErhxLNCs_Diagonal_Lunge.png
** C1. Diagonal Plate Raise
    https://fast.wistia.net/embed/iframe/rbpvtlmv0u
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/tk1Yrk2HROeEpiMfZanH_Diagonal_Plate_Raise.png
** C2. Skater Squat
    https://fast.wistia.net/embed/iframe/lzfucud6fw
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/WYhg6syhQJ62j9gYZtVr_Skater_Squat.png
** D1. Up-Down Plank
    https://fast.wistia.net/embed/iframe/goivucj1y6
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/v6HkADKuQJeZB4yizw6S_Up-Down_Plank.png
** D2. Scissor Jump for Height
    https://fast.wistia.net/embed/iframe/mrcvapx3bb
    https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/JuOkSXNdQGWmn9PVVwBQ_Scissor_Jump_for_Height.png

