#+TITLE: Lower 2
#+SUBTITLE: uap-off-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-3.html

* A1. Forward Frog Jumps
  {{{youtube(09KPdgduavA)}}}

  - the purpose of this drill is to get full extension of ankles, knees, and hips
  - propel yourself explosively upward and a little bit forward

* A2. Power Skips for Distance
  - 3 reps each leg.
  - Aim for full hip extension and distance

* B1. Deadlift
  {{{youtube(PrBBOFdOHk8)}}}

  - Shoulders retracted.
  - Spine neutral. Look at a spot on the floor about 5 feet in front of you.
  - Get your hips back and chest over the bar
  - Arms should be straight at the start of the lift
  - Back remains flat as hips come forward and weight lifts up

* C1. Walking Lunges
  {{{youtube(NTiYltLIVB0)}}}

  - Aim for 90 degree angle of the lunging knee but do not let your back knee touch the ground.
  - Step directly into the next lunge without pausing at the top of the movement.
  - Keep your shoulders locked back and chest up.

* C2. Stability Ball Hip Extension with Lying Leg Curl
  {{{youtube(h1Us6x0fuPI)}}}

  - First raise your hips to parallel by squeezing your glutes.
  - Maintain the tension in your glutes to keep your hip us as you bring the ball toward you
  - Knees, hips, and shoulders should all be in a line at the top of the movement.
  - Allow the ball to move away from you in a controlled fashion.
  - Lower your hips again to complete the movement.

* Alternate two legged version
  {{{youtube(MEqwmz-nfVo)}}}

  - If single leg is too difficult (it's definitely not easy!) it's better to have good form on the two legged version.
