#+TITLE: Speed (week 5-6)
#+SUBTITLE: uap-six-week-speed-agility-conditioning
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-6-week.html

* Forward Frog Jumps
  {{{youtube(nhDXP6h33qM)}}}


  - the purpose of this drill is to get full extension of ankles, knees, and hips
  - propel yourself explosively upward and a little bit forward

* Three Step Approach Jumps
  {{{youtube(ldBS5OCXVTk)}}}


  - Reach up with the arm opposite the leg pushing off the ground for maximum reach height (lay-up style)

* Waltz Step Agility

  - Works on quick feet, hip action, and change of direction.
  - Center of mass should remain at about the same height as the feet move underneath

Practice the movement slowly to understand the footwork pattern before working on speed.

** Slow practise:
   {{{youtube(GtmDQJ8a13Q)}}}


** When the footwork pattern is mastered, go at full speed:
   {{{youtube(Bn3BWRKhwi0)}}}


   - aim for both speed and accuracy of foot placement
   - center of mass should remain on the line created by the cones
   - keep your head up, not looking at your feet

* Zig Zag Sprints
  {{{youtube(YdgYleKenGM)}}}


  - You should be using the jab step or waltz step in each turn. practice both!
