#+TITLE: Philosophy of a Taper
#+SUBTITLE: uap-taper
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-taper.html


   This video gives a few suggestions on how to modify your workouts
   starting about 2 weeks before tryouts. Bullet points below are a good
   summary and give you the basic points you need to know.

   Keep in mind that the season is too long to taper before every
   tournament. If you spend too much time worrying about absolute peak
   performance every weekend, then you will not make gains during the
   season and may even go backwards. Taper for only the most important
   events of your season. For some of you, this may mean tapering for
   tryouts, for others of you it won't.

   The goal is to have your body feeling loose, energized, and mobile and
   your nervous system ready. These suggestions are made with these goals
   in mind.

   1.  Two weeks before the event, cut all of your normal training by one
      third. Still do all of the workouts, but instead of 3 sets, do 2.
      This goes for both running and strength training.
   2.  One week from the event, cut another third of your training. So now
      to one set instead of three, for example. Again, you still want to
      do work at a high intensity to maintain the neural adaptations. But
      you want to allow your body some space for extra physical recovery.
   3.  The day before the event, do an extended warm up (maybe some extra
      mobility drills or running form drills) and 1/3 of an alactic
      workout. Basically you want to do a little bit of full intensity
      activity. This may help prevent you from coming out "flat" at the
      start of your event. It is about keeping teh nervous system primed
      for action!
   4.  Mobility and the nervous system excitement change daily. This is why
      we still do something with those systems the day before.
   5.  Conditioning is easily maintained so you could easily cut out your
      lactic workouts and be totally fine. while you are tapering, don't
      worry about your conditioning. You're not going to lose anything.
      The upside of being well rested is greater than the possible
      downside of a minimal temporary decrease in conditioning level.
