#+TITLE: Lower
#+SUBTITLE: uap-pre-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-pre-season-3.html

* A1. High Pull from the Floor
    {{{youtube(ZcSdx0oc4kw)}}}


    - If mobility issues prevent you from easily getting in position, do these from a higher position.
    - Elbows should be locked out at the start (to avoid jerking your shoulders out of socket please!)
    - Get your hips back. The weight starts close to your shins with your chest over the weight.
    - Shoulders retracted. Neutral spine. All the good form usual stuff applies and is vitally important! Take your time, focus.
    - Explode and cause the weight to come straight up. You should feel like you are "jumping" the weight up with your hips, not pulling the weight up with your arms. You may notice your hips drop again as the weight comes up. This is fine.

* B1. 1 & 1/4 Rear Foot Elevated Split Squat
    {{{youtube(YJkfv07vEEg)}}}


    - Get front thigh to parallel
    - Quarter rep is at the bottom
    - Keep shoulders back, chest tall

* B2. Hip Thrusts
    {{{youtube(tWd5ikvnaPc)}}}


    - Weight rests approximately on hip flexors
    - Place a sweatshirt or folded up yoga mat between your hips and the weight for added comfort.
    - Heels should be directly under the knees at the top position.
    - Focus on squeezing your glutes. Keep back straight, not arched.

* C1. Accentuated King DB RDL
    {{{youtube(At9rCSBgy8c)}}}


    - Use one leg on the eccentric phase (lowering the weight), two legs on the concentric phase (raising the weight)
    - Get your hips through at the top
    - Shoulders retracted throughout the movement
    - Knee should be bent about 10 degrees throughout the movement
    - Think about moving your hips back when lowering the weight. Make yourself stand up by using your glutes/hamstrings to push your hips forward.

* C2. Supine Band Hip Flexion
    {{{youtube(y3hdjZE85yY)}}}


    - Keep the opposite leg on the ground.
    - Get the working leg past parallel and hold it there
