#+TITLE: Speed (week 3-4)
#+SUBTITLE: uap-six-week-speed-agility-conditioning
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-6-week.html

* Fast feet to five step acceleration
  {{{youtube(hZcFe5qG-OQ)}}}


  - about three seconds of light fast feet, then explode out and accelerate for 5 steps
  - attempt to get up to full speed in five steps

* Three Point Start
  {{{youtube(j76bJSWSKzg)}}}


  - Hips up.&nbsp; Feet should be closer to hands than you might think.
  - Lean over the hand on the ground.&nbsp; You should feel that you are close to falling over.
  - You should feel some tension in the hamstrings like you are a spring ready to bounce.
  - Accelerate as explosively as possible out of the starting position.

* Jab Step Agility

  - Works on quick feet, lateral motion, and change of direction.
  - Center of mass should remain at about the same height as the feet move underneath

  Practice the movement slowly to understand the footwork pattern before working on speed.

** Slow jab step:
   {{{youtube(pESWXL27LwY)}}}

   
** When the footwork pattern is mastered, go at full speed:
   {{{youtube(zmafY8nYl50)}}}


   - aim for both speed and accuracy of foot placement
   - center of mass should deviate equally to each side of the line
   - keep your head up, not looking at your feet

* 5-10 drill
  First demo is slow. Second is full speed
  
  {{{youtube(3TDsG76rx_E)}}}


  - first five yards hips are NOT fully committed. hips are diagonal to the line of the cones
  - coming out of the turn, the outside foot crosses over, pointing the hips parallel to the line of the cone (aka hips face the direction you want to move and are fully committed)
