#+TITLE: Warmup
#+SUBTITLE: uap-six-week-speed-agility-conditioning
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-6-week.html

If you're not already using a dynamic warm-up, use this one as a good place to start. A good warm-up generally has three parts:

- Part 1 focuses on increasing blood flow with moderate intensity movements.
- Part 2 uses mobility exercises to take the joints through a full range of motion and to help athletes establish good movement patterns.
- Part 3 is about exciting the nervous system and is the most important part of getting ready to play.

* Part 1
  Get the body moving and increase blood flow.
  
  1. Run at 60% speed to half field
  2. Backwards run with large steps half field.
  3. Run at 60% speed to half field
  4. Backward skip/shuffle (40 yards)
     {{{youtube(luGia1b-9eo)}}}

  5. Casual (low intensity) skip to half field.
  6. Low intensity shuffle half field. Change direction the athlete is facing every four steps.
     {{{youtube(uoU3FrWvCvw)}}}


* Part 2
  
  1. lunges: done with a twist or a reach as shown below
     {{{youtube(IgTbR4PtY6w)}}}

  2. High Knee Hugs
     {{{youtube(Z3Zk7jxJ0kw)}}}

  3. Figure 4 Hugs
     {{{youtube(_oxu_UNGnXI)}}}

  4. Drinking Bird
     {{{youtube(MvahyT8y90U)}}}

  5. Walking Quad Stretch
     {{{youtube(7OyY73Vl5AI)}}}

  6. Over Unders (3-5 times each direction)
     {{{youtube(DsDOGpx2exg)}}}

  7. Standing T-Spine Rotation (5 rotations each side)
     {{{youtube(ySGckEct_QI)}}}

  8. Penguin Walk (about 10 yards forward and 10 yards backward)
     {{{youtube(ck16SRln8Kc)}}}


* Part 3
  All exercises should be done for about 15 yards unless otherwise noted. *Allow some rest between exercises* so that you can move at high intensity with quick, light feet. The purpose here is NOT to elevate your heart rate, but to prepare your nervous system to recruit the maximum number of fast twitch muscle fibers as quickly as possible.
  
  1. Cycle kicks
     {{{youtube(4tnxvHbIjVs)}}}

  2. Lateral high knee skip
     {{{youtube(LP2iJZJ_Fek)}}}

  3. Backwards run
     {{{youtube(-3vo1XCSUpU)}}}

  4. Lateral skips
     {{{youtube(6dBXyLSqN4Y)}}}

  5. Falling Leaf
     {{{youtube(v46SaKqPtjc)}}}

  6. Leprechaun Skips
     {{{youtube(yM3hAvxOIao)}}}

