#+TITLE: Core 1
#+SUBTITLE: uap-off-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-3.html

* A note on scheduling your core sessions
    The core workout of this phase also includes some power exercises. For this reason, keep two days in between your leg and core workouts. (You always want to do this anyway, because our core programs include the hips)

* A1. Pre-Stretch Crunch
    {{{youtube(E3tF_mL21wY)}}}


    - Feel a slight stretch in the abs at the initiation of the movement
    - Contract the abs until the back is flat
    - Hold the weight directly above your eyes and aim up for the sky as you contract

* A2. Single Leg Heel-elevated Hip Extension
    {{{youtube(VXU1aStrggY)}}}


    - Engage the core to maintain aneutral spine.
    - Squeeze your glutes and avoid arching your back

* A3. Up and Down Bosu Plank
    {{{youtube(p5EwPMDr0m4)}}}


    - Maintain plank postition with shoulders, hips, knees, and ankles in line.
    - Move quickly for the specifies number of seconds.
    - Alternate which arm goes down first each set or switch halfway through each set.
