#+TITLE: Strength 2
#+SUBTITLE: uap-preparation
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-preparation.html

* A1. Barbell Bench Press
    {{{youtube(r7WFii7ezGM)}}}


    - retract your shoulders so that they are flat on the bench
    - grip should be slightly wider than shoulder width

* A2. Split Squat to Cable Row
    {{{youtube(LqGpV_hHBSM)}}}


    - pull with the opposite arm of the leg that is forward.
    - hips should move straight up and down
    - use full range of motion in the shoulder but do not lean forward or backwards in the rowing motion.

* B1. Sumo Squat
    {{{youtube(IFC0H29Hxts)}}}


    - chest tall, look straight ahead
    - toes are pointed out about 30 degrees
    - stance is wide so that knees are at about 90 degrees at the bottom of the movement

* B2. Single Leg SLDL
    {{{youtube(JiAYM5SGoAU)}}}


    - keep shoulders hips and knee in a line as you push your hip back and lower your torso.
    - knee of working leg should be bent about 10 degrees
    - keep the hips level, shoulders back
    - try doing the whole set without allowing the other leg to touch the ground

* C1. 1/2 Cubans
    {{{youtube(sVStZCVqqIc)}}}


    - keep your shoulders retracted
    - avoid shrugging the weight
    - elbows should be stationary while rotating the weight

* C2. Standing Hip Flexion
    {{{youtube(PQAePRjGomM)}}}


    - Place on foot on a box or bench that causes your knee to be close to 90 degrees.
    - Keep your hips level for the duration of this exercise!
    - Pull your leg straight up (it won't go very far) and hold for three seconds before lowering it back to the bench.
