#+TITLE: Alternative Power-focused session
#+SUBTITLE: uap-pre-season-1
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-pre-season-1.html


   This is a fun workout to try for those already familiar with the UAP. It
   can be used as an alternative power focused workout during a preseason
   or in-season phase of the UAP. Laying out is one of the hardest ultimate
   skills to teach - I think there are some fun ways to train in the gym
   for laying out on the field (Leslie Wu published a great article on
   [[https://ultitraining.wordpress.com/2016/02/22/4-steps-to-a-picture-perfect-layout/)][teaching the layout]].

   As Leslie wrote, the explosive triple extension (ankle/knees/hips) is
   one of the keys to a good layout. We can practice that by doing power
   movements like Hang Cleans or DB Snatches, and also by doing hops up on
   a short box to emphasize extension at the top! There's a significant
   overhead component as well, strengthening the shoulder and its
   surrounding areas to provide stability when you hit the ground (i.e.
   less shoulder separations). And the core component is huge - being able
   to utilize thoracic (mid-back) extension instead of lumbar (low back)
   and being able to stabilize successfully will make your layouts stronger
   and help reduce injury risk.

*  Warm Up

    -   [[{{{youtubelink(T_MdN-i7VqA)}}}][Inchworms]]
    -   Mid-Back Sweeps
      -   Face down, forehead on hands - inhale deeply, exhale fully and
        right at the end, lift just your upper chest off the floor. Move
        from the mid-back and relax the shoulders. Add a sweep side to
        side after you do a few reps.
    -   Crab Table (elevated bridge, picking up one foot at a time)

*  The Workout

    -   3 x 4 [[{{{youtubelink(VNNfgktuzlQ)}}}][DB High Pull]]
    -   3 x 4 [[{{{youtubelink(VNNfgktuzlQ)}}}][DB Snatch]]
    -   45 seconds of [[{{{youtubelink(z_Edc-R8EVU)}}}][Crawling Patterns]] in between
      sets of 8
    -   2 x 1 minute each side, alternate exercises
    -   [[https://www.instagram.com/p/9m-9jrFRN6/?taken-by=rencaldwell][Landmine Press]]
    -   Step Up with hop (mid-foot on a box, step up and do triple
      extension - if you feel comfortable, take your arm overhead,
      alternating arms, and if that feels good, add a hop at the top)
    -   2 x 45 seconds each side, alternate exercises
    -   [[{{{youtubelink(sNA1zOkBdcA)}}}][Bench Hip Extensions]]
    -   [[{{{youtubelink(SDNjdE2RcYE)}}}][Plank Pull]]

*  Practical

    -   4x [[https://www.instagram.com/p/BCIpiZLFRDV/?taken-by=rencaldwell][Crawl to layout]]
      (thanks Leslie!)
    -   5x [[https://www.instagram.com/p/BCItAAbFRJs/?taken-by=rencaldwell][Sprint from floor]]
      (for when you miss the layout but have to get up and play D
    -   1 minute of [[https://www.instagram.com/p/BCIpiZLFRDV/?taken-by=rencaldwell][Elevated Deadbugs]]
      (do on the floor if you can't maintain neutral spine!)
