#+TITLE: Grass Conditioning 1, 2 & 3
#+SUBTITLE: uap-pre-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-pre-season-3.html

On this page you'll find everything you need for the conditioning workouts. Remember all of these workouts should be preceded by a proper dynamic warmup. See the [[https://ultyresults.mykajabi.com/products/uap/categories/89306/posts/231475][Linear]] and [[https://ultyresults.mykajabi.com/products/uap/categories/89306/posts/231481][Multidirectional Warmup]] pages for details.

In this phase you have three types of conditioning workouts. Conditioning is the focus of this phase, so you should try to do conditioning 4-6 times per week. The Tabata conditioning should be done no more than twice. The Linear Conditioning and Recovery workout should be done at least once.
* Conditioning 1: Tabata
  The Tabata conditioning should be done no more than twice in a week. Your reps are simple: sprint for 20 seconds, rest for 10.
* Conditioning 2: With Disc
* A1. Kill Drill
  {{{youtube(Oy1AoKkqJjM)}}}

* A2. Marking & Pivoting
  {{{youtube(AYjPT2s6wmc)}}}

* A3. Full Body Shuttle
  {{{youtube(U-6P_zMnABc)}}}

* Conditioning 3: Linear & Recovery
  This should be an easy day. You'll run at about 70% of sprint speed (the pace of a fast mile) for 30seconds, then rest for seconds. That's one rep. Do however many reps feel comfortable.
