#+TITLE: Lower 1
#+SUBTITLE: uap-off-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-3.html

* A1. Lateral Bound and Stick
    {{{youtube(JZKSKTTmS0o)}}}


    - The point of this exercises is to land softly and stick the landing.
    - Experiment to see how far you can jump while landing softly and under control.

* A2. Tuck Jumps
    {{{youtube(uCgaMLjr20I)}}}


    - Minimize ground contact time.
    - Land quietly on the mid-forefoot and explode up again as quickly as possible.
    - Pull your knees up as high as possible.
    - Keep the spine neutral and chest tall! Knees come up to meet the chest, not the other way around.

* B. Squat
    {{{youtube(Or-vzoYN5Sc)}}}


    - Butt back, neutral spine, push through the heels
    - Think about exploding out of the bottom of your squat

* C1. DB SLDL
    {{{youtube(JiAYM5SGoAU)}}}


    - keep shoulders hips and knee in a line as you push your hip back and lower your torso.
    - knee of working leg should be bent about 10 degrees
    - keep the hips level, shoulders back
    - try doing the whole set without allowing the other leg to touch the ground

* C2. Lying Band Hip Flexion
    {{{youtube(y3hdjZE85yY)}}}


    - Keep the opposite leg on the ground.
    - Get the working leg past parallel and hold it there

* D. Low Squat Jumps
    {{{youtube(tiaf7MAyJ-w)}}}


    - minimize ground contact time
    - stay low with knee angle near ninety degrees
