#+TITLE: Grass Conditioning 1 & 2
#+SUBTITLE: uap-pre-season-2
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-pre-season-2.html


   Conditioning 1 should be preceded by the [[https://www.ultyresults.com/products/uap/categories/89306/posts/231481][Nonlinear Warmup]].

   Conditioning 2 should be preceded by the [[https://www.ultyresults.com/products/uap/categories/89306/posts/231475][Linear Warmup]].

*  Conditioning 1: Multi-directional

* A. 5-10-5, five frog jumps and repeat

     {{{youtube(57fJcrpPif8)}}}


* B. Zig Zag Sprints

     {{{youtube(YdgYleKenGM)}}}


     -   Set up 2 rows of cones about 5-7 yards apart. In each row, three
       cones are placed about 8 yards apart. The two rows are off set by 4
       yards to create a zig-zag pattern.

* C. Figure Eight Sprints

     {{{youtube(zwHfN0hlEVc)}}}


     -   Attempt to cut on the inside foot rather than the outside foot (like
       in the jab step).
     -   To use the inside foot, you'll likely slow down a bit before the
       cone and "switch your hips"

*  Conditioning 2: Linear and Disc

* A. Shuttle with Throwing

     Backhand

     {{{youtube(vLcyN6ZUlns)}}}


     and forehand

     {{{youtube(hSaaVxxsxB8)}}}


     -   Distances are 10, 20, 30 yards

* B. Pull and Sprint 70 yards
