#+TITLE: Morning Mobility
#+SUBTITLE: uap-post-season
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-post-season.html

You may be relaxing your workout and warm up regimen in the post season, and that's fine. We want this month to be a time of regeneration. An important part of regeneration is getting blood and nutrients to the joints and muscle tissues of the body.

Doing some mobility work every day is a great way to keep the joints healthy and mobile so they're ready to get back in action when you're ready to start your training again.

This is a morning mobility routine that I use to loosen up my spine, shoulders, and hips on mornings when I'm feeling not so great. When I do this routine regularly, I'm more relaxed throughout the day.

The beauty of this routine is that it takes less than ten minutes once you learn all of the moves. Make this part of your morning routine just like brushing your teeth. You can also sprinkle these movements throughout the day. Eagle shoulders are my favorite to do if I'm spending a lot of time at the computer.

Before this routine I also like to roll the bottom of my feet with a lacrosse ball.

* 1. Neck Rolls
  {{{youtube(qCeqTc4jGi0)}}}

  - Exhale as head drops forward, inhale as ear goes tot he shoulder.
  - Relax and let your ear drop toward your shoulder as it's ready
  - Repeat three times to each side

* 2. Shoulder Rolls
  {{{youtube(Fo4EaiixOFk)}}}

  - Grab one wrist in the hand of the other behind you.
  - Relax the arms and roll the shoulders up and back
  - Repeat three times

* 3. Eagle Arms
  {{{youtube(0-qJmOEIMlw)}}}

  - Cross one arm over the other and bend the elbows to 90 degrees
  - Attempt to grasp your hands with palms facing one another (good luck)
  - Press the palms together tightly. You should feel a stretch in the back of your shoulders.
  - Slowly raise the elbows parallel to the shoulders, press palms together, and hold. (Don't do this if it hurts!)
  - Slowly lower the elbows as far as you can, press palms together, and hold.
  - Repeat twice.
  - Re-cross your arms this time with the opposite arm on top.
  - Repeat the same sequence twice more.

* 4. Standing T-Spine Rotation
  {{{youtube(qTwb2O01KtE)}}}

  - Stand in a quarter squat position with ips level and knees together.
  - Keeping hips level and knees togethre, rotate one arm behind you, following it with your head/eyes.
  - Bring the arm back to meet the other one and repeat on the other side.
  - Repeat three times each side.

* 5. Hip Circles
  {{{youtube(kD1dEOAPr8c)}}}

  - You are a very slow moving hula girl

* 6. Cat/Cow
  {{{youtube(4Wmnt79L61A)}}}

  - Hands under shoulders, knees under hips
  - Arch your back to the sky, let your head drop down.
  - Reverse your spine by arching your back. Think of making a half circle. Do not over-extend your neck.

* 7. Goddess Squat
  {{{youtube(f4skGkdVZEc)}}}

  - (Not everyone will be able to do this movement. Substitute with relaxing into a low squat position, choose something else, or just skip this.)
  - Grab your toes and pull yourself down into a low squat position.
  - With elbows against the inside of the knees, press your palms flat together
  - Press palms together, press kneess to elbows. Should feel a stretchin the lower back and/or hips.

* 8. Karate Kid Hips
  {{{youtube(SobWGzstlWk)}}}

  - Dynamic balance is fun first thing in the morning!
  - Stand on one leg in a quarter squat position.
  - Raise the other leg straight in front of you
  - Swing the leg out in a half-circle until it is behind you
  - Repeat three times with each leg

    You can throw in some extra moves for your own problem areas. The above routine is a good place to start. *Try it out and let me know what you think in the comments below!*
