#+TITLE: Core 2
#+SUBTITLE: uap-off-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-3.html

* A note on scheduling your core sessions
    The core workout of this phase also includes some power exercises. For this reason, keep two days in between your leg and core workouts. (You always want to do this anyway, because our core programs include the hips)
* A1. Dead Bug Legs
    {{{youtube(9Dz-gdhwl2s)}}}


    - Keep core engaged
    - Attempt to keep the hips completely stationary while legs move.

* A2. Plank Walks
    {{{youtube(_QmurtmSi7s)}}}


    - Keep shoulders, hips, and ankles in a line
    - Walk ten yards sideways and back twice for a total of forty yards.
    - One direction, lead with the hands (hand, foot, hand, foot). the other direction lead with the feet.

* A3. Side Plank with Leg Raise
    {{{youtube(1_k1Vr9xe4I)}}}


    - Lift hips off the ground to come to a plank position
    - Lift leg as high as is comfortable keeping toes pointed forward. Watch for internal or external rotation of the hips and avoid it.
