#+TITLE: Upper Body Lifting Warmup
#+SUBTITLE: uap-warmups
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-warmups.html

There is no one perfect warm up. How much of a warm up you need will depend on things like your age, the rep range of the program you're about to do, or how you're feeling on a particular day.

Below are some exercises you can do for a warm up to prepare for the upper body training session. In general, you just want to do some pulling and some pushing at lower resistance than what you'll be using in the workout.

If you are starting off with lifts in the rep range of five or fewer, do some warm up sets of that lift before your working sets. A suggested warm up series would be:

1. A set of 8-10 reps at about 1/3 of the weight you plan for your first working set
2. A set of 5-8 reps at about 1/2 of the weight of your working set,
3. A final set of 3-5 reps at a bit over 3/4 the weight of your working set.

You should not get near failure on these. They are to get your muscles warm and your neurons firing.

Below are some suggestions for mobility drills and light warmup exercises.

* Inchworms
  {{{youtube(bfWcQlN-sq8)}}}

* Down Dog to Plank to Up Dog (what's "up dog?" Not mutch, what's up with you?)
  {{{youtube(A6mSKpqJR38)}}}

* Pushup with Rotation
  {{{youtube(8BAGcv4Xw1k)}}}

* T-spine rotation (this is more mobility drill than warmup drill)
  {{{youtube(xi48S_aB_FA)}}}

* Lat Pulldowns
  {{{youtube(G4q1hXoESos)}}}

* Retraction to row
  {{{youtube(30YE0OH5DNE)}}}

* Shoulder Rotations
  {{{youtube(JiavICGaFp8)}}}
