#+TITLE: Core 2
#+SUBTITLE: uap-preparation
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-preparation.html

   A core circuit will take 10-12 minutes. The core circuits can be done 2-3 times a week alternating between the two circuits ([[https://www.ultyresults.com/products/uap/categories/69150/posts/185453][Core 1]] and Core 2). Alternatively, they can be done before/after playing/conditioning, or after an SAQ session.

   Perform the circuit 3 times through with norest or minimal rest between exercises and sets.
* 1 & 1/4 Wood Chop (start light 8-10 each side. Add one rep each week.)
    {{{youtube(COCqjeny0Ds)}}}


    - explosive chop. quarter rep at the end
    - slowly lower the weight back to starting position.
    - look at your hands as you move

* Stability Ball Pull In (Start with 6-8, add 1-2 reps each week as able)
    {{{youtube(FHXRMdX0_qk)}}}


    - with your feet on the ball, bring your knees toward your chest.
    - slowly return to the staring plank position

* Side Plank Cable Row (use light weight. 8-10 reps each side)
    {{{youtube(1mPJJkmrqX8)}}}


    - maintain a solid side plank position
    - pull the cable or resistance band and retract the shoulders as far back as possible. think about squeezing the shoulder blades together.

* Congrats on completing a preparation phase workout!
    [[https://www.ultyresults.com/p/uap-high-fives][Get your virtual High Five here!]]
