#+TITLE: Tissue Quality Routine
#+SUBTITLE: uap-post-season
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-post-season.html

   The post season is a great opportunity to spend time on things you may have neglected during your months of hard training. Now is a good time to make progress on your problem areas while you're not adding additional stress.

   If you haven't been doing tissue quality work, now is a good time to learn and to get yourself started on some good habits to take you into next season.

   {{{youtube(dr3bj1rSCTc)}}}


   Scan everything every day (or at least every other) and to spend a few extra minutes on any trigger points or areas of tenderness you might find. Remember, any tissue work is better than no tissue work! Do something every day!

   Here is a good place to start for building your own tissue quality routine.

* Back
    {{{youtube(jCnpxn4NGPM)}}}


* Back Extensions
    {{{youtube(JrjwkMy6Xmk)}}}


* Lats
    {{{youtube(dsAb3hGcERk)}}}


* Glute Max and Glute Medius
    {{{youtube(5yzMYKugwWc)}}}


* IT Band
    {{{youtube(zJfSjVkqQlI)}}}


* Quads
    You can throw in a kind of active release move at the end for more of a benefit.

    {{{youtube(hYcZTCpGFI4)}}}


* Groin
    {{{youtube(gNutsgBFJ0o)}}}


* Hamstrings
    {{{youtube(cSFnbD0gmA8)}}}


* Calves
    I prefer a ball for calves and hamstrings to better target the inside and outside

    {{{youtube(YQX0dRw4uqc)}}}


* Feet
    Oh, and don't forget the feet! If nothing else, use a lacrosse ball on the bottom of the feet once a day to keep them maintained and feeling good!
