#+TITLE: Core 2
#+SUBTITLE: uap-off-season-1
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-1.html

Perform the circuit 3 times through with no rest or minimal rest between exercises and sets
* A1. Stir the pot
  {{{youtube(FTumEC5enyU)}}}

  - Maintain a good plank position with shoulders hips and ankles in a line.
  - Place your feet wider apart to make the exercises slightly easier if necessary.
  - With shoulders retracted and fingers interlaced, move the stability ball in small circles.

* A2. Stability Ball Pike
  {{{youtube(jAA5x303V-A)}}}

  - Start in a plank position with shoulders retracted.
  - With the core engaged, initiate the movement of the ball with your lower abs.
  - Bring the ball forward and hips up until your upper body is in a handstand position.

* A3. Stability Ball DB Russian Twist
  {{{youtube(T88m08cIlPo)}}}

  - Use your glutes to keep your hips up
  - Keeping your shoulders retracted and arms straight, rotate to one side and then the other for one rep.
