#+TITLE: Upper 1
#+SUBTITLE: uap-off-season-4
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-4.html

* A1. Push Press
  {{{youtube(Z9b5LJ1Am_A)}}}

  - Use momentum from the hips to help you press more than you otherwise would.
  - The bar starts resting high on your chest. Grip slightly wider than shoulder width.
  - Dip into about a quarter squat and as you stand push the weight overhead.
  - Legs should be straight at the end of the movement and arms should be locked out.
  - Lower the weight in a controlled fashion back to the starting position.

* A2. Paused Semisupinated Grip Pull-Up
  {{{youtube(ZB3GmD4-1hE)}}}

  - "semi supinated" means that your palms are facing one another. If you do not have a bar that allows for this, use a supinated grip (palms toward you)
  - keep your chest up. squeeze shoulder blades together at the top of the movement.
  - If you do not have an assisted chinup machine, you can use a lat pulldown instead.

* B1. Split Squat to Cable Row
  {{{youtube(LqGpV_hHBSM)}}}

  - pull with the opposite arm of the leg that is forward.
  - hips should move straight up and down
  - use full range of motion in the shoulder but do not lean forward or backwards in the rowing motion.

* B2. Alternating Iso Hold DB Bench
  {{{youtube(5C9B2mrhZ1g)}}}

  - Hold one dumbbell as you press the other.
  - Keep tension in the pectoral of the side you are holding.

* This strength session should be followed by [[https://www.ultyresults.com/products/ultimate-athlete-project/categories/89285/posts/241195][Core Circuit 1]]
