#+TITLE: Lower Body Lifting Warmup
#+SUBTITLE: uap-warmups
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-warmups.html

There is no one perfect warm up. How much of a warm up you need will depend on things like your age, the rep range of the program you're about to do, or how you're feeling on a particular day. Below are some exercises you can do for a warm up to prepare for the upper legs training session.

In general, you just want to do some knee dominant and some hip dominant exercises at lower resistance than what you'll be using in the workout.

I usually start with a few mobility oriented movements (little/no resistance). Examples shown below. Then I will do light weight for 8-10 reps of hamstring curls and 8-10 reps of split squats before jumping in to my first exercise of the program.

If you are starting off with lifts in the rep range of five or fewer, do some warm up sets of that lift before your working sets. A suggested warm up series would be: one set of 8-10 reps at about 1/3 of the weight you plan for your first working set. One set of 5-8 reps at about 1/2 of the weight of your working set. And one set of 3-5 reps at a bit over 3/4 the weight of your working set. You should not get near failure on these. They are to get your muscles warm and your neurons firing.

Below are some suggestions for mobility drills and light warmup exercises.

* 1. The Witmer squat
  5-8 reps

* 2. Frog squats (hits the hamstring really well)
  5-8 rep

* 3. Five point lunge
  Three reps each leg

* 4. Three point SLDL
  Three reps each leg

* Extra
  If you're looking to get a little fancy, try the two full body mobility drills below:

  1. Backwards spiderman
  2. Walking bow and arrow
