#+TITLE: SAQ 1 - Multi-directional
#+SUBTITLE: uap-in-season-1-alt
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-in-season-1-alt.html

* A. One Foot Forward Hop into Marking Base
    {{{youtube(eCf9JI8fkcU)}}}


    - Hop forward off of one foot and land in your marking base.
    - Hold for 2-5 seconds.
    - Reset and repeat for 10 jumps off your left foot and 10 jumps off of your right foot.

* B: Fast Feet Shuffle
    {{{youtube(UvgZCVcsReA)}}}


    Standing in your marking base, you're going to do the fast feet drill, but this time you'll be shuffling between two cones at about 5 yards (4.5 meters) apart.

    Your goal is to chop your feet as quickly as you can for 10 seconds as you move from cone to cone, maximizing the number of ground contacts while moving laterally from cone to cone.

    Alternate which direction you start. Do 1 where you start toward the left and 1 where you start toward the right.

* C. Side Shuffle with Pause and Reach
    {{{youtube(GcyU5FrmcPY)}}}


    Set up two cones/items to mark off 5 yards or 4.5 meters. You'll side shuffle from one object to the other, and reach/pause. (Remember, you're visualizing reaching to block a high release, low release or standard "around" throw at that cone). Focus on minimizing weight shifts. Your goal is to be able to reach without letting your weight shift to your outside leg. Things to add today:

    - Reaching higher in your high release "blocking" - try not to come up on your toes
    - Getting lower to block a low release throw - sit down lower and reach out wider when you get to the cone
    - Explosively pushing off with both legs/feet when you change directions after the pause
    - *Repeat this so you go 8x each way (8x to the left, 8x to the right)*

    *Then couple this workout with immediately moving into [[https://www.ultyresults.com/products/ultimate-athlete-project/categories/685101/posts/2252951][Skills 1]]!*
