#+TITLE: Warmup
#+SUBTITLE: uap-six-week-speed-agility-conditioning
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-6-week.html

If you're not already using a dynamic warm-up, use this one as a good place to start. A good warm-up generally has three parts:

- Part 1 focuses on increasing blood flow with moderate intensity movements.
- Part 2 uses mobility exercises to take the joints through a full range of motion and to help athletes establish good movement patterns.
- Part 3 is about exciting the nervous system and is the most important part of getting ready to play.

* Part 1
  Get the body moving and increase blood flow.
  
  1. Run at 60% speed to half field
  2. Backwards run with large steps half field.
  3. Run at 60% speed to half field
  4. Backward skip/shuffle (40 yards)
     https://www.youtube.com/embed/luGia1b-9eo
     https://img.youtube.com/vi/luGia1b-9eo/hqdefault.jpg
  5. Casual (low intensity) skip to half field.
  6. Low intensity shuffle half field. Change direction the athlete is facing every four steps.
     https://www.youtube.com/embed/uoU3FrWvCvw
     https://img.youtube.com/vi/uoU3FrWvCvw/hqdefault.jpg

* Part 2
  
  1. lunges: done with a twist or a reach as shown below
     https://www.youtube.com/embed/IgTbR4PtY6w
     https://img.youtube.com/vi/IgTbR4PtY6w/hqdefault.jpg
  2. High Knee Hugs
     https://www.youtube.com/embed/Z3Zk7jxJ0kw
     https://img.youtube.com/vi/Z3Zk7jxJ0kw/hqdefault.jpg
  3. Figure 4 Hugs
     https://www.youtube.com/embed/_oxu_UNGnXI
     https://img.youtube.com/vi/_oxu_UNGnXI/hqdefault.jpg
  4. Drinking Bird
     https://www.youtube.com/embed/MvahyT8y90U
     https://img.youtube.com/vi/MvahyT8y90U/hqdefault.jpg
  5. Walking Quad Stretch
     https://www.youtube.com/embed/7OyY73Vl5AI
     https://img.youtube.com/vi/7OyY73Vl5AI/hqdefault.jpg
  6. Over Unders (3-5 times each direction)
     https://www.youtube.com/embed/DsDOGpx2exg
     https://img.youtube.com/vi/DsDOGpx2exg/hqdefault.jpg
  7. Standing T-Spine Rotation (5 rotations each side)
     https://www.youtube.com/embed/ySGckEct_QI
     https://img.youtube.com/vi/ySGckEct_QI/hqdefault.jpg
  8. Penguin Walk (about 10 yards forward and 10 yards backward)
     https://www.youtube.com/embed/ck16SRln8Kc
     https://img.youtube.com/vi/ck16SRln8Kc/hqdefault.jpg

* Part 3
  All exercises should be done for about 15 yards unless otherwise noted. *Allow some rest between exercises* so that you can move at high intensity with quick, light feet. The purpose here is NOT to elevate your heart rate, but to prepare your nervous system to recruit the maximum number of fast twitch muscle fibers as quickly as possible.
  
  1. Cycle kicks
     https://www.youtube.com/embed/4tnxvHbIjVs
     https://img.youtube.com/vi/4tnxvHbIjVs/hqdefault.jpg
  2. Lateral high knee skip
     https://www.youtube.com/embed/LP2iJZJ_Fek
     https://img.youtube.com/vi/LP2iJZJ_Fek/hqdefault.jpg
  3. Backwards run
     https://www.youtube.com/embed/-3vo1XCSUpU
     https://img.youtube.com/vi/-3vo1XCSUpU/hqdefault.jpg
  4. Lateral skips
     https://www.youtube.com/embed/6dBXyLSqN4Y
     https://img.youtube.com/vi/6dBXyLSqN4Y/hqdefault.jpg
  5. Falling Leaf
     https://www.youtube.com/embed/v46SaKqPtjc
     https://img.youtube.com/vi/v46SaKqPtjc/hqdefault.jpg
  6. Leprechaun Skips
     https://www.youtube.com/embed/yM3hAvxOIao
     https://img.youtube.com/vi/yM3hAvxOIao/hqdefault.jpg
