#+TITLE: SAQ 1 & 2
#+SUBTITLE: uap-off-season-2
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-2.html

   These workouts are to be preceded by the [[https://www.ultyresults.com/products/uap/categories/89306/posts/231481][Nonlinear Warmup]].

* SAQ 1

   This is the main SAQ day and should ideally be done 48 hours before and after the leg lifting days.

* A. Box Jumps
     {{{youtube(tVnU1kwoIMM)}}}


     - Find a bench, box, or other object that allows you to land on it with a knee angle of greater than 90 degrees. Otherwise, the surface is definitely too high.
     - Land softly with the entire foot on the surface.

* B. Low Squat to Scissor Jumps
     {{{youtube(Mf7cZzcCyuc)}}}


     - Knees should be close to 90 degrees in the low squat jumps.
     - Get as high as possible in the scissor jumps with minimal ground contact times between jumps.

* C. Single Leg Bench Hops
     {{{youtube(zT_jMofv4V8)}}}


     - Slam the working leg onto the bench and push yourself as high into the air as possible.
     - You should move slightly forward with each jump to ensure maximal hip extension.

* D1. Lean/Fall/Run
     {{{youtube(Y2aCnrTvqZo)}}}


     - Get up on the balls of your feet and lean forward.
     - Let yourself lean as far as you can before falling out into a sprint.
     - Some of these will be more coordinated than others. No worries. Your body will learn the most forward leaning position it can handle through trial and error.

* D2. Three Point Start
     {{{youtube(j76bJSWSKzg)}}}


     - Hips up. Feet should be closer to hands than you might think.
     - Lean over the hand on the ground. You should feel that you are close to falling over.
     - You should feel some tension in the hamstrings like you are a spring ready to bounce.
     - Accelerate as explosively as possible out of the starting position.

* SAQ 2
* A. Countermovement Lateral Hops
     {{{youtube(zsikQYzW1xw)}}}


     - Use your arms to generate height.
     - Land softly between the cones.

* B. 5-10-5 Drill
     {{{youtube(lIq87ZhL8bE)}}}


     - Alternate starting directions each set.
     - This builds on your lateral starts from last phase.
     - First five yards, hips should remain mostly forward.
     - Second ten yards turn the hips but open early to change directions with maximal efficiency. Same thing for the last turn.

* C. Shuffle to Sprint
     {{{youtube(hX3TKqIFCbM)}}}


     - Stay low in the shuffle.
     - Use a crossover step to turn your hips and orient yourself quickly in the direction of sprinting.
