#+TITLE: Lower 2
#+SUBTITLE: uap-off-season-4
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-4.html

* A1. Frog Jumps
    {{{youtube(v51cWelUBpM)}}}


    - Drop the hips and explode up as soon as your hands graze the floor.
    - Drop the hips! Don't bend at the waist. Neutral spine, it's all in the hips.

* A2. High Pulls from the Floor
    {{{youtube(ZcSdx0oc4kw)}}}


    - If mobility issues prevent you from easily getting in position, do these from a higher hang position.
    - Elbows should be locked out at the start (to avoid jerking your shoulders out of socket please!)
    - Get your hips back. The weight start close to your shins with your chest over the weight.
    - Shoulders retracted. Neutral spine. All the good form usual stuff applies and is vitally important! Take your time, focus.
    - Explode and cause the weight to come straight up. You should feel like you are "jumping" the weight up with your hips, not pulling the weight up with your arms. You may notice your hips drop again as the weight comes up. This is fine.

* B. Squat Jumps
    {{{youtube(U4l8ZYKkQBQ)}}}


    - Use no more than 25% of your bodyweight on the bar
    - Maintain a neutral spine
    - Keep the bar in contact with your back (it should not bounce)
    - Minimize ground contact time as you explode up as high as possible.

* C. Heel Elevated Hip Lifts
    {{{youtube(EFLq2nE7up8)}}}


    - Elevate the foot of the working leg on a step
    - Can be elevated on a Bosu ball for added difficulty.
    - Nonworking leg remains straight
    - Pause at the top of the movement

* This session should be followed with [[https://www.ultyresults.com/products/ultimate-athlete-project/categories/89285/posts/320840][Core Circuit 2]]
