#+TITLE: Lower
#+SUBTITLE: uap-off-season-1
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-1.html

* A1. Front Foot Elevated Paused Split Squat
	 - Timing: 3-2-2-0

	 1.  3x sets of 8-10 reps, 30s rest b/wn sets
	 2.  3x sets of 7-9 reps, 30s rest b/wn sets
	 3.  3x sets of 6-8 reps, 30s rest b/wn sets
	 4.  2x sets of 5-7 reps, 30s rest b/wn sets

	    {{{youtube(NpzqPBBn1qo)}}}

	    - push through the heel of your front foot
	    - hips should move straight up and down
	    - pause for 2 seconds at the bottom position
	    - keep shoulders back and chest tall

* A2. Barbell RDL
  {{{youtube(XxM-QNjznF0)}}}

  - Knee angle should be about 10 degrees
  - Lower the weight as mobility allows, keeping a neutral spine. You should feel a slight stretch in the hamstrings.
  - Hips move back as you lower the weight. Your weight should be distributed more toward your heels
  - Pushing the hips forwards with your glutes brings you to a standing position. Push your hips all the way through.

* B1. Front DB Box Squat with Ankle Extension
  {{{youtube(kiki_7Rdl_s)}}}

  - reach your butt back and just tap the bench or box

* B2. Bosu Plantar Flexion Paused Hip-ups
  {{{youtube(6R6oOZKDQTc)}}}

  - keep your toes pointed down (that's plantar flexion)
  - use your butt. you may also feel it in your calves and hamstrings
  - keep abs in, spine neutral

* C1. Standing Calf Raises
  {{{youtube(Nn1uB7qVmxM)}}}

  - Place your midfoot on a step or box. Hold onto something to help your balance.
  - Get full range of motion on these and really squeeze your calves at the top for a full contraction
  - Do these as quickly and explosively as possible without jumping.

* C2. Standing Hip Flexion
  {{{youtube(VcJsZ--kcSY)}}}

  - Place on foot on a box or bench that causes your knee to be close to 90 degrees.
  - Keep your hips level for the duration of this exercise!
  - Pull your leg straight up (it won't go very far) and hold for three seconds before lowering it back to the bench.
