#+TITLE: Upper
#+SUBTITLE: uap-off-season-1
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-1.html

* A1. Paused Incline DB Press
  {{{youtube(k4mI7a_tSbw)}}}

  - during the pause at the bottom your pectorals should feel tension

* A2. Low Incline Prone Paused DB Row
  {{{youtube(XqkV8RL4iaM)}}}

  - really squeeze your shoulder blades together at the top as you hold for 2 counts

* B1. Pullovers
  {{{youtube(52c015jdieo)}}}

  - Keep elbows at approximately the same angle throughout the movement
  - As you lower the weight, you should feel a slight stretch in your lower pectoral muscles
  - Squeeze your chest to initiate the movement and bring the weight above your face.
  - Keep your hips up and core engaged for the duration of the set.
  - At the end of your set, place the weight on the bench beside you or drop it to the floor after lowering it behind your head.

* B2. 1 & 1/4 Semi-supinated grip Pull-ups
  {{{youtube(vE9L7GC4y8E)}}}

  - Grip the bar with palms facing one another
  - If you do not have a bar that allows this, grip with palms facing toward you
  - If you have no way to do assisted chinups, you can do lat pulldowns instead (though these are not quite as good)

* C1. Speed Push-ups
  {{{youtube(7lHuWdR6iQs)}}}

  - do as many pushups as possible. be explosive! don't pace yourself, go fast.

* C2. Incline Y to T Raise
  {{{youtube(2Z-Ib02O8J0)}}}

  - Initiate the movement at the shoulders. Thumbs face up to the Y position.
  - Retract the shoulders fully and rotate to thumbs down as you bring the weight back to the T position.
