#+TITLE: Upper 1
#+SUBTITLE: uap-off-season-3
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-off-season-3.html

* A. Semisupinated Grip Chin Up
  {{{youtube(R-j7IvquHwE)}}}

  - "semi supinated" means that your palms are facing one another. If you do not have a bar that allows for this, use a supinated grip (palms toward you)
  - keep your chest up. Squeeze shoulder blades together at the top of the movement.
  - If you do not have an assisted chinup machine, you can use a lat pulldown instead.

* B1. Single Arm DB Bench Press
  {{{youtube(bUxfgjTklao)}}}

  - Do all reps on one side. Then the other.
  - Do not hold any weight in the non working limb. Engage the core to resist rotation.
  - Maintain tension in the pecs at the bottom of the movement.

* B2. Single Arm Standing Cable Row
  {{{youtube(mRk69bN2v7Q)}}}

  - Stand in a quarter squat position.
  - Do all reps on one side, then the other.
  - Engage the core to resist rotation.

* C1. Cuban to Press
  {{{youtube(v19DV8xcMDA)}}}

  - Retract the shoulders and maintain a neutral spine.
  - Do not hyperextend the back*.*
  - Elbows are stationary during rotation.
  - If pressing overhead hurts at all, don't do it!
