#+TITLE: Upper body strength
#+SUBTITLE: uap-five-body-weight-workouts
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-five-body-weight-workouts.html

This short session is a good intro to some body weight work for the upper body. Go beyond the pushup and into some interesting alternatives in this short, but effective training session!

Do each of the exercises for the recommended repetitions. Repeat the circuit 2-3 times.

| Exercise |  Reps |
|----------+-------|
| A1       | 10-25 |
| A2       |  6-20 |
| A3       | 10-20 |

* A1. Rocking Pushups

  {{{wistialink(pc2ii2vih2)}}}
  https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/QI2x1GaQke1AuYofcnqK_Rocking_Pushups_1.jpg

  This is a great exercise for naturally cueing good pushup form. It is far superior to pushups from the knees for those who cannot do full pushups because the spine tends to maintain the preferred alignment throughout the movement and the elbows stay tucked in.

  For those strong enough for a high volume of regular pushups, the rocking pushup is an excellent upper body warm-up exercise that cues good form, and moves the shoulder through a large range of motion.

* A2. Side-to-Side Monkey Crawl

  {{{wistialink(ibf0bw3evg)}}}
  https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/yeSc9utYS9uflj1cGWHp_Side-to-Side_Monkey_Crawl_1.jpg

  One rep includes both sides.

  This Monkey Crawl exercise gives us a bit of rotational core stimulus and is good for training shoulder stability. As you get better at the exercise you can move your hips higher and move more slowly.

* A3. Wall-Catch Pushups

  {{{wistialink(q9s2q8n6m3)}}}
  https://kajabi-storefronts-production.global.ssl.fastly.net/kajabi-storefronts-production/themes/1759674/settings_images/AtTKbDfRFepN6gszwk2w_Wall-Catch_Pushups_1.jpg

  The goal of this exercise is to catch yourself with the elbows at about 90 degrees. This engages the muscle fibers of the pectorals very quickly. It adds a bit of power stimulus to your upper body routine.

  If this exercise is too easy, you can also do catch pushups on the floor from your knees. Start with just a few reps. It's easy to overdo it on fast eccentric exercises until you get used to them!
