#+TITLE: Skills 1 & 2
#+SUBTITLE: uap-in-season-1-alt
#+SETUPFILE: ../workout.setup
#+HTML_LINK_UP: uap-in-season-1-alt.html

* Skills 1
* A1. Flat Mark Shuffle - forehand
  {{{youtube(EEr2OyD9EWQ)}}}

  Set up three cones. the center cone represents the pivot foot. Focus on shuffling laterally along a "flat mark plane." The video sets up a flat mark scenario. Note that Robyn is standing closer to one cone (that represents the open or forehand side).

* A2. Flat Mark Shuffle - backhand
  As above, but for the backhand side of this drill too.

  {{{youtube(s4mz8J4vrI8)}}}

  Do the drill 8 times forehand, and 8 times backhand.
* Skills 2
* A. Stationary Reaching at Slow Pace
  {{{youtube(1ihSoCpmiTI)}}}

  Your partner holds a disc and slowly fakes in each throwing lane. Your goal is to stand in your athletic marking base. Go for a set amount of time (20-30 seconds) and switch with your partner.

* B. Reacting to Disc Fakes
  {{{youtube(zuLljGe4dEs)}}}

  You'll notice Molly (defender in black) resets to the center cone every time and Anna (thrower in white) waits for Molly to reset before she pivots out toward one of the outside cones. You'll also see that Anna is about 3-5 yards away from Molly. This is great, because it gives Molly more time to react (since this is just the first "reactive to a disc" drill that we are doing!).

  Thrower should only pivot out to one direction, wait for the mark to get to the cone, and reset in the middle. Go for a 10 second stall count, and repeat 5 times each.

* C. Reacting Live
  {{{youtube(NCHFRK0Lkws)}}}

  Your partner is now pivoting and faking quickly, and you get to shuffle side to side while you're reaching. Do a 10 second stall count. Do this three times (you and your partner each go 3x on offense)

  *Note:* if you are in The Ultimate Skills Project, you can substitute whatever module you're working on here. If you enjoyed these marking skill activities, you can find more drills and progressions in The Ultimate Skills Project along with modules for skills such as decision making, mental toughness, backhand hucks, handler O and D, and more. [[https://www.ultyresults.com/p/skills-development-lab][Learn more about The Ultimate Skills Project here]].
